-- Table 1: Registry of unique nodes (The "Phonebook")
CREATE TABLE IF NOT EXISTS nodes (
  pubkey TEXT PRIMARY KEY,
  ip_address TEXT,
  gossip_port INT DEFAULT 9001,
  rpc_port INT DEFAULT 6000,
  country TEXT DEFAULT 'Unknown',
  city TEXT DEFAULT 'Unknown',
  latitude FLOAT,
  longitude FLOAT,
  isp TEXT,
  first_seen_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE
);

-- Indexes for nodes table
CREATE INDEX IF NOT EXISTS idx_nodes_ip_address ON nodes(ip_address);
CREATE INDEX IF NOT EXISTS idx_nodes_is_active ON nodes(is_active);
CREATE INDEX IF NOT EXISTS idx_nodes_country ON nodes(country);

-- Table 2: Time-series data for graphs (The "History")
CREATE TABLE IF NOT EXISTS snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_pubkey TEXT REFERENCES nodes(pubkey) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Metadata
  version TEXT,
  credits INT DEFAULT 0,
  
  -- Performance Stats (Nullable because RPC might fail)
  rpc_active BOOLEAN DEFAULT FALSE,
  cpu_percent FLOAT,
  ram_used BIGINT,
  ram_total BIGINT,
  uptime_seconds BIGINT,
  storage_used BIGINT,
  
  -- Calculated Score
  total_score FLOAT DEFAULT 0
);

-- Indexes for snapshots table (CRITICAL FOR PERFORMANCE)
CREATE INDEX IF NOT EXISTS idx_snapshots_pubkey_time ON snapshots(node_pubkey, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_created_at ON snapshots(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_rpc_active ON snapshots(rpc_active);
