-- Table 1: Registry of unique nodes (The "Phonebook")
CREATE TABLE nodes (
  pubkey TEXT PRIMARY KEY,
  ip_address TEXT,
  gossip_port INT DEFAULT 9001,
  rpc_port INT DEFAULT 6000,
  country TEXT DEFAULT 'Unknown',
  city TEXT DEFAULT 'Unknown',
  latitude FLOAT,
  longitude FLOAT,
  isp TEXT,
  first_seen_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE
);

-- Table 2: Time-series data for graphs (The "History")
CREATE TABLE snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_pubkey TEXT REFERENCES nodes(pubkey),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Metadata
  version TEXT,
  credits INT DEFAULT 0,
  
  -- Performance Stats (Nullable because RPC might fail)
  rpc_active BOOLEAN DEFAULT FALSE,
  cpu_percent FLOAT,
  ram_used BIGINT,
  ram_total BIGINT,
  uptime_seconds BIGINT,
  storage_used BIGINT,
  
  -- Calculated Score
  total_score FLOAT DEFAULT 0
);

-- Index for fast querying of history
CREATE INDEX idx_snapshots_pubkey_time ON snapshots(node_pubkey, created_at DESC);
